# Created with YamlCreate.ps1 v2.8.0 $debug=MDSU.CRLF.7-6-5.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: BlueStack.BlueStacks
PackageVersion: 5.22.166.1003
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: -s
  SilentWithProgress: -s
  InstallLocation: -pf "<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- bluestacksgp
- bluestacksx
- bstlogcollector
FileExtensions:
- apk
- xapk
Installers:
- Architecture: x64
  InstallerUrl: https://ak-build.bluestacks.com/public/app-player/windows/nxt/5.22.166.1003/e0cbf0a49445273dc3c94ced970fd7d4/FullInstaller/x64/BlueStacksFullInstaller_5.22.166.1003_amd64_native.exe
  InstallerSha256: DBE8B99D3D06F520865D7ADD1C8651B4841D55BEF07FB04C9F2D025263ADCAB7
  ProductCode: BlueStacks_nxt
ManifestType: installer
ManifestVersion: 1.12.0
