# Created with YamlCreate.ps1 v2.8.0 $debug=MDSU.CRLF.7-6-5.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.12.0.schema.json

PackageIdentifier: BlueStack.BlueStacks
PackageVersion: 5.22.166.1003
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.12.0
