# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: BlueStack.BlueStacks
PackageVersion: 4.280.1.1002
PackageLocale: ko
Publisher: BlueStack Systems, Inc.
PublisherUrl: https://www.bluestacks.com/
PublisherSupportUrl: https://support.bluestacks.com/
PrivacyUrl: https://www.bluestacks.com/terms-and-privacy.html#privacy
Author: BlueStack Systems, Inc.
PackageName: 블루스택
PackageUrl: https://support.bluestacks.com/hc/articles/360021469391
License: 숨겨진 원천
LicenseUrl: https://www.bluestacks.com/terms-and-privacy.html#terms
Copyright: >
  © 2011 년부터 2021 년까지 블루스택 시스템, Inc. 전 세계 모든 권리 보유
CopyrightUrl: https://www.bluestacks.com/copyright-dispute-policy.html
ShortDescription: 세상에서 가장 빠르고 가벼운 안드로이드 앱플레이어 및 클라우드 게임 플랫폼으로 Windows 및 Mac에서 RPG, 전략, 액션 모바일 게임을 원활하게 플레이해 보세요.
Description: 세상에서 가장 빠르고 가벼운 안드로이드 앱플레이어 및 클라우드 게임 플랫폼으로 Windows 및 Mac에서 RPG, 전략, 액션 모바일 게임을 원활하게 플레이해 보세요.
ReleaseNotes: |-
  1. 이제 게임 충돌 없이 ブルーアーカイブ (com.YostarJP.BlueArchive) 를 플레이할 수 있습니다.
  2. 검은 화면, 그래픽 및 충돌 문제가 더 이상 존재하지 않는 환상적인 AOD-龍神無双- (com.coc.jplh)의 세계로 떠나보세요!
  3. Churchill Solitaire Card Game (com.productiveedge.churchill)에서 신기록을 세우세요. 개막작 이후에는 더 이상 충돌하지 않습니다.
  4. 日向坂46とふしぎな図書室 (jp.co.sonymusic.game.hinatosho)에서 완벽한 게임을 즐기세요!
  5. 이제 시작 시 충돌 없이 ラストオリジン –次世代美少女×戦略RPG- (com.pig.laojp.aos)를 플레이할 수 있습니다. 이 장대한 RPG에서 인류를 구해주세요.
  6. 라이즈 오브 킹덤즈 : Lost Crusade (com.lilithgame.roc.gp)를 플레이하는 동안 Ark of Osiris에 분홍색 패치가 표시되지 않습니다. 멋진 게임 경험을 즐기십시오.
  7. 프린세스 커넥트! Re:Dive (com.kakaogames.pcr)는 오류 메시지를 표시하지 않고 실행 시 충돌합니다.
ReleaseNotesUrl: https://support.bluestacks.com/hc/articles/360021469391
Documentations:
- DocumentLabel: BlueStacks 4
  DocumentUrl: https://support.bluestacks.com/hc/categories/360000451812
ManifestType: locale
ManifestVersion: 1.12.0
