# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: BlueStack.BlueStacks
PackageVersion: 4.280.1.1002
PackageLocale: vi
Publisher: BlueStack Systems, Inc.
PublisherUrl: https://www.bluestacks.com/
PublisherSupportUrl: https://support.bluestacks.com/
PrivacyUrl: https://www.bluestacks.com/terms-and-privacy.html#privacy
Author: BlueStack Systems, Inc.
PackageName: BlueStacks
PackageUrl: https://support.bluestacks.com/hc/articles/360021469391
LicenseUrl: https://www.bluestacks.com/terms-and-privacy.html#terms
Copyright: >
  © 2011 đến 2021 Bluestack Systems, Inc. Mọi quyền được bảo lưu trên toàn thế giới
CopyrightUrl: https://www.bluestacks.com/copyright-dispute-policy.html
ShortDescription: Phần mềm giả lập Android tích hợp điện toán đám mây nhanh nhất và nhẹ nhất thế giới. Bạn có thể chơi game Android trên PC và Mac. Sự lựa chọn tuyệt hảo để chơi các dòng game nhập vai, chiến thuật và hành động.
Description: Phần mềm giả lập Android tích hợp điện toán đám mây nhanh nhất và nhẹ nhất thế giới. Bạn có thể chơi game Android trên PC và Mac. Sự lựa chọn tuyệt hảo để chơi các dòng game nhập vai, chiến thuật và hành động.
ReleaseNotes: |-
  1. Bây giờ bạn có thể chơi ブ ル ー ア ー カ イ ブ (com.YostarJP.BlueArchive) mà không gặp bất kỳ lỗi nào trong trò chơi.
  2. Bước vào thế giới tuyệt vời của AOD- 龍神 無双 - (com.coc.jplh), nơi các vấn đề về màn hình đen, đồ họa và sự cố không còn nữa!
  3. Tạo kỷ lục mới trong Churchill Solitaire Card Game (com.productiveedge.churchill) vì nó sẽ không bị carash sau phần phim mở đầu nữa.
  4. Hãy tận hưởng trải nghiệm chơi game hoàn hảo trong 日 向 坂 46 と ふ し ぎ な 図 書 室 (jp.co.sonymusic.game.hinatosho)!
  5. Bây giờ bạn có thể chơi ラ ス ト オ リ ジ ン - 次世代 美 少女 × 戦 略 RPG- (com.pig.laojp.aos) mà không gặp sự cố khi khởi chạy.
  6. Trong khi chơi Rise of Kingdoms: Lost Crusade (com.lilithgame.roc.gp), bạn sẽ không thấy bất kỳ mảng màu hồng nào trong Ark of Osiris.
  7. 프린세스 커넥트! Re: Dive (com.kakaogames.pcr) sẽ không hiển thị thông báo lỗi và sau đó gặp sự cố khi khởi chạy cho bạn
ReleaseNotesUrl: https://support.bluestacks.com/hc/articles/360021469391
Documentations:
- DocumentLabel: BlueStacks 4
  DocumentUrl: https://support.bluestacks.com/hc/categories/360000451812
ManifestType: locale
ManifestVersion: 1.12.0
