# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: BlueStack.BlueStacks
PackageVersion: 4.280.1.1002
PackageLocale: pl
Publisher: BlueStack Systems, Inc.
PublisherUrl: https://www.bluestacks.com/
PublisherSupportUrl: https://support.bluestacks.com/
PrivacyUrl: https://www.bluestacks.com/terms-and-privacy.html#privacy
Author: BlueStack Systems, Inc.
PackageName: BlueStacks
PackageUrl: https://support.bluestacks.com/hc/articles/360021469391
License: własnościowe
LicenseUrl: https://www.bluestacks.com/terms-and-privacy.html#terms
Copyright: >
  © 2011 do 2021 Bluestack Systems, Inc. Wszelkie prawa zastrzeżone
CopyrightUrl: https://www.bluestacks.com/copyright-dispute-policy.html
ShortDescription: Najszybszy, najlżejszy i najwyżej oceniany emulator Androida i platforma do gier w chmurze. Graj w gry mobilne na Windows i Mac. Idealny do gier RPG, strategicznych i akcji.
Description: Najszybszy, najlżejszy i najwyżej oceniany emulator Androida i platforma do gier w chmurze. Graj w gry mobilne na Windows i Mac. Idealny do gier RPG, strategicznych i akcji.
ReleaseNotes: |-
  1.Możesz teraz grać w ブ ル ー ア ー カ イ ブ (com.YostarJP.BlueArchive) bez żadnych awarii gry. Obecnie można je znaleźć tylko w podręcznikach do historii.
  2. Wejdź do fantastycznego świata AOD- 龍神 無双 - (com.coc.jplh), w którym nie ma już czarnego ekranu, problemów graficznych i awarii!
  3. Zrób nowe rekordy w grze karcianej Churchill Solitaire (com.productiveedge.churchill), ponieważ nie będzie się ona już zawieszać po pierwszym filmie. Czas, by Winston był dumny!
  4. Przygotuj się na bezbłędne wrażenia z gry w 日 向 坂 46 と ふ し ぎ な 図 書 室 (jp.co.sonymusic.game.hinatosho)!
  5. Możesz teraz grać w ラ ス ト オ リ ジ ン - 次世代 美 少女 × 戦 略 RPG- (com.pig.laojp.aos) bez awarii podczas uruchamiania. Walcz o ludzkość w tej epickiej grze RPG!
  6. Podczas gry w Rise of Kingdoms: Lost Crusade (com.lilithgame.roc.gp) nie zobaczysz żadnych różowych łat w Ark of Osiris. Naciesz oczy wspaniałą grą.
  7. 프린세스 커넥트! Re: Dive (com.kakaogames.pcr) nie wyświetli komunikatu o błędzie, a następnie zawiesi się podczas uruchamiania. Czas zostać księżniczką rycerzem w lśniącej zbroi!
ReleaseNotesUrl: https://support.bluestacks.com/hc/articles/360021469391
Documentations:
- DocumentLabel: BlueStacks 4
  DocumentUrl: https://support.bluestacks.com/hc/categories/360000451812
ManifestType: locale
ManifestVersion: 1.12.0
