# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: BlueStack.BlueStacks
PackageVersion: 4.280.1.1002
PackageLocale: es
Publisher: BlueStack Systems, Inc.
PublisherUrl: https://www.bluestacks.com/
PublisherSupportUrl: https://support.bluestacks.com/
PrivacyUrl: https://www.bluestacks.com/terms-and-privacy.html#privacy
Author: BlueStack Systems, Inc.
PackageName: BlueStacks
PackageUrl: https://support.bluestacks.com/hc/articles/360021469391
License: Privativo
LicenseUrl: https://www.bluestacks.com/terms-and-privacy.html#terms
Copyright: >
  © 2011 hasta 2021 Bluestack Systems, Inc. Todos los derechos reservados en todo el mundo
CopyrightUrl: https://www.bluestacks.com/copyright-dispute-policy.html
ShortDescription: El emulador de Android y la plataforma de juegos en la nube más rápidos y ligeros del mundo. Juega juegos móviles en Windows y Mac. Perfecto para juegos de rol, estrategia y acción.
Description: El emulador de Android y la plataforma de juegos en la nube más rápidos y ligeros del mundo. Juega juegos móviles en Windows y Mac. Perfecto para juegos de rol, estrategia y acción.
ReleaseNotes: |-
  1. Ahora puedes jugarブ ル ー ア ー カ イ ブ(com.YostarJP.BlueArchive) sin que el juego se bloquee. Ahora solo se pueden encontrar en los libros de historia.
  2. ¡Ingrese al fantástico mundo de AOD- 龍神 無双 - (com.coc.jplh) donde ya no existen problemas de pantalla negra, gráficos y fallas!
  3. Haga nuevos récords en Churchill Solitaire Card Game (com.productiveedge.churchill), ya que no se bloqueará después de la película de apertura. ¡Es hora de enorgullecer a Winston!
  4. ¡Prepárate para una experiencia de juego impecable en日 向 坂 46 と ふ し ぎ な 図 書 室(jp.co.sonymusic.game.hinatosho)!
  5. Ahora puedes jugarラ ス ト オ リ ジ ン - 次世代 美 少女 × 戦 略 RPG- (com.pig.laojp.aos) sin que se bloquee en el lanzamiento. ¡Lucha por la humanidad en este épico juego de rol!
  6. Mientras juegas a Rise of Kingdoms: Lost Crusade  (com.lilithgame.roc.gp), no verás ningún parche rosa en Ark of Osiris. Deleite sus ojos con una espléndida experiencia de juego.
  7. 프린세스 커넥트! Re: Dive (com.kakaogames.pcr) no mostrará un mensaje de error y luego se bloqueará en el inicio. ¡Es hora de ser la princesa caballero con armadura brillante!
ReleaseNotesUrl: https://support.bluestacks.com/hc/articles/360021469391
Documentations:
- DocumentLabel: BlueStacks 4
  DocumentUrl: https://support.bluestacks.com/hc/categories/360000451812
ManifestType: locale
ManifestVersion: 1.12.0
