# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: BlueStack.BlueStacks
PackageVersion: 4.280.1.1002
PackageLocale: id
Publisher: BlueStack Systems, Inc.
PublisherUrl: https://www.bluestacks.com/
PublisherSupportUrl: https://support.bluestacks.com/
PrivacyUrl: https://www.bluestacks.com/terms-and-privacy.html#privacy
Author: BlueStack Systems, Inc.
PackageName: BlueStacks
PackageUrl: https://support.bluestacks.com/hc/articles/360021469391
LicenseUrl: https://www.bluestacks.com/terms-and-privacy.html#terms
CopyrightUrl: https://www.bluestacks.com/copyright-dispute-policy.html
ShortDescription: Platform Gaming Cloud dan Emulator Android Tercepat dan Teringan di Dunia. Mainkan game mobile di Windows & Mac. Cocok untuk game RPG, strategi & aksi
Description: Platform Gaming Cloud dan Emulator Android Tercepat dan Teringan di Dunia. Mainkan game mobile di Windows & Mac. Cocok untuk game RPG, strategi & aksi
ReleaseNotes: |-
  1. Sekarang kamu dapat memainkan game ブルーアーカイブ (com.YostarJP.BlueArchive) tanpa mengalami permasalahan crash.
  2. Masuki dunia fantasi AOD-龍神無双- (com.coc.jplh) di mana masalah layar hitam, grafis, dan tabrakan tidak lagi ada!
  3. Buat rekor baru di Churchill Solitaire Card Game (com.productiveedge.churchill) karena tidak akan macet lagi setelah muncul cuplikan film. Saatnya membuat bangga Winston!
  4. Bersiaplah untuk pengalaman bermain yang sempurna di 日向坂46とふしぎな図書室 (jp.co.sonymusic.game.hinatosho)!
  5. Sekarang Anda dapat memainkan ラストオリジン –次世代美少女×戦略RPG- (com.pig.laojp.aos) tanpa mengalami crash. Ayo berjuang untuk sisi kemanusiaan pada RPG yang epik ini!
  6. Saat memainkan Rise of Kingdoms: Lost Crusade (com.lilithgame.roc.gp), kamu tidak akan kembali melihat bercak merah muda di Ark of Osiris. Manjakan mata Anda dengan pengalaman bermain game yang luar biasa.
  7. 프린세스 커넥트! Re: Dive (com.kakaogames.pcr) tidak akan menampilkan pesan error ataupun stuck  saat game ini dijalankan. Saatnya menjadi ksatria putri berbaju zirah!
ReleaseNotesUrl: https://support.bluestacks.com/hc/articles/360021469391
Documentations:
- DocumentLabel: BlueStacks 4
  DocumentUrl: https://support.bluestacks.com/hc/categories/360000451812
ManifestType: locale
ManifestVersion: 1.12.0
