# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: BlueStack.BlueStacks
PackageVersion: 4.280.1.1002
PackageLocale: fr
Publisher: BlueStack Systems, Inc.
PublisherUrl: https://www.bluestacks.com/
PublisherSupportUrl: https://support.bluestacks.com/
PrivacyUrl: https://www.bluestacks.com/terms-and-privacy.html#privacy
Author: BlueStack Systems, Inc.
PackageName: BlueStacks
PackageUrl: https://support.bluestacks.com/hc/articles/360021469391
License: Propriétaire
LicenseUrl: https://www.bluestacks.com/terms-and-privacy.html#terms
Copyright: >
  © 2011 à 2021 Bluestack Systems, Inc. Tous droits réservés dans le monde entier
CopyrightUrl: https://www.bluestacks.com/copyright-dispute-policy.html
ShortDescription: L'émulateur Android et la plateforme de Cloud Gaming les plus rapides et les plus légers au monde. Jouez à des jeux mobiles sur Windows et Mac. Parfait pour les jeux de rôle, de stratégie et d'action.
Description: L'émulateur Android et la plateforme de Cloud Gaming les plus rapides et les plus légers au monde. Jouez à des jeux mobiles sur Windows et Mac. Parfait pour les jeux de rôle, de stratégie et d'action.
ReleaseNotes: |-
  1. Vous pouvez désormais jouer à ブルーアーカイブ (com.YostarJP.BlueArchive) sans que le jeu ne crash. Ils ne peuvent désormais être trouvés que dans les livres d'histoire.
  2. Entrez dans le monde fantastique d'AOD-龍神無双- (com.coc.jplh) où les écrans noirs, les problèmes graphiques et les crashs n'existent plus!
  3. Faites de nouveaux records dans Churchill Solitaire Card Game (com.productiveedge.churchill) car il ne plantera plus après le film introductif. Il est temps de rendre Winston fier!
  4. Préparez-vous à vivre une expérience de jeu sans faille dans 日向坂46とふしぎな図書室 (jp.co.sonymusic.game.hinatosho)!
  5. Vous pouvez désormais jouer à ラストオリジン –次世代美少女×戦略RPG- (com.pig.laojp.aos) ans subir de crash au lancement. Combattez pour l'humanité dans ce RPG épique!
  6. En jouant à Rise of Kingdoms: Lost Crusade (com.lilithgame.roc.gp), vous ne verrez aucune tache rose dans Ark of Osiris. Régalez vos yeux avec une expérience de jeu splendide.
  7. 프린세스 커넥트! Re:Dive (com.kakaogames.pcr) n'affichera pas un message d'erreur et ne crashera pas au lancement pour vous. Il est temps de devenir le chevalier de la princesse en armure brillante!
ReleaseNotesUrl: https://support.bluestacks.com/hc/articles/360021469391
Documentations:
- DocumentLabel: BlueStacks 4
  DocumentUrl: https://support.bluestacks.com/hc/categories/360000451812
ManifestType: locale
ManifestVersion: 1.12.0
