# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: BlueStack.BlueStacks
PackageVersion: 4.280.1.1002
PackageLocale: pt-BR
Publisher: BlueStack Systems, Inc.
PublisherUrl: https://www.bluestacks.com/
PublisherSupportUrl: https://support.bluestacks.com/
PrivacyUrl: https://www.bluestacks.com/terms-and-privacy.html#privacy
Author: BlueStack Systems, Inc.
PackageName: BlueStacks
PackageUrl: https://support.bluestacks.com/hc/articles/360021469391
License: Privativo
LicenseUrl: https://www.bluestacks.com/terms-and-privacy.html#terms
Copyright: >
  © 2011 até 2021 Bluestack Systems, Inc. Todos os direitos reservados mundialmente
CopyrightUrl: https://www.bluestacks.com/copyright-dispute-policy.html
ShortDescription: O emulador Android e plataforma de jogos na nuvem mais rápido e leve do mundo. Jogue jogos Mobile no PC e Mac. Perfeito para RPGs, jogos de estratégia e de ação.
Description: O emulador Android e plataforma de jogos na nuvem mais rápido e leve do mundo. Jogue jogos Mobile no PC e Mac. Perfeito para RPGs, jogos de estratégia e de ação.
ReleaseNotes: |-
  1. Agora você pode jogar ブルーアーカイブ (com.YostarJP.BlueArchive) sem travar o jogo. Eles agora só podem ser encontrados nos livros de história.
  2. Entre no mundo fantástico de AOD-龍神無双- (com.coc.jplh) onde tela preta, gráficos e problemas de travamento não existem mais!
  3. Faça novos recordes no Churchill Solitaire Card Game (com.productiveedge.churchill) pois ele não travará mais após o filme de abertura. É hora de deixar Winston orgulhoso!
  Prepare-se para uma experiência de jogo impecável em 日向坂46とふしぎな図書室 (jp.co.sonymusic.game.hinatosho)!
  5. Agora você pode jogar ラストオリジン –次世代美少女×戦略RPG- (com.pig.laojp.aos) sem travar na inicialização. Lute pela humanidade neste RPG épico!
  6. Ao jogar Rise of Kingdoms: Lost Crusade (com.lilithgame.roc.gp), você não verá nenhum patch rosa na Arca de Osíris. Deleite seus olhos com uma experiência de jogo esplêndida.
  7. 프린세스 커넥트! Re:Dive (com.kakaogames.pcr) não mostrará uma mensagem de erro e depois travará na inicialização para você. É hora de ser a princesa cavaleiro de armadura brilhante!
ReleaseNotesUrl: https://support.bluestacks.com/hc/articles/360021469391
Documentations:
- DocumentLabel: BlueStacks 4
  DocumentUrl: https://support.bluestacks.com/hc/categories/360000451812
ManifestType: locale
ManifestVersion: 1.12.0
