# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: BlueStack.BlueStacks
PackageVersion: 4.280.1.1002
PackageLocale: ja
Publisher: BlueStack Systems, Inc.
PublisherUrl: https://www.bluestacks.com/
PublisherSupportUrl: https://support.bluestacks.com/
PrivacyUrl: https://www.bluestacks.com/terms-and-privacy.html#privacy
Author: BlueStack Systems, Inc.
PackageName: BlueStacks
PackageUrl: https://support.bluestacks.com/hc/articles/360021469391
License: プロプライエタリなソフトウェア
LicenseUrl: https://www.bluestacks.com/terms-and-privacy.html#terms
Copyright: >
  © 2011 through 2021 Bluestack Systems, Inc. All rights reserved worldwide
CopyrightUrl: https://www.bluestacks.com/copyright-dispute-policy.html
ShortDescription: 世界最速、最軽量のAndroidアプリプレイヤー兼クラウドゲームプラットフォーム。WindowsとMacでモバイルゲームをプレイ可能。RPG、ストラテジー、アクションゲームに最適。
Description: 世界最速、最軽量のAndroidアプリプレイヤー兼クラウドゲームプラットフォーム。WindowsとMacでモバイルゲームをプレイ可能。RPG、ストラテジー、アクションゲームに最適。
ReleaseNotes: |-
  1. ブルーアーカイブ (com.YostarJP.BlueArchive)：クラッシュ不具合を修復
  2. ラストオリジン –次世代美少女×戦略RPG- (com.pig.laojp.aos) ：クラッシュ不具合を修復
  3. AOD-龍神無双- (com.coc.jplh) ：グラフィックスおよびクラッシュ不具合を修復
  4. 日向坂46とふしぎな図書室 (jp.co.sonymusic.game.hinatosho) ：起動不可を修復
  5. Rise of Kingdoms: Lost Crusade (com.lilithgame.roc.gp)：グラフィックス不具合を修復
  6. Churchill Solitaire Card Game (com.productiveedge.churchill)：クラッシュ不具合を修復
ReleaseNotesUrl: https://support.bluestacks.com/hc/articles/360021469391
Documentations:
- DocumentLabel: BlueStacks 4
  DocumentUrl: https://support.bluestacks.com/hc/categories/360000451812
ManifestType: locale
ManifestVersion: 1.12.0
