# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: BlueStack.BlueStacks
PackageVersion: 4.280.1.1002
PackageLocale: tr
Publisher: BlueStack Systems, Inc.
PublisherUrl: https://www.bluestacks.com/
PublisherSupportUrl: https://support.bluestacks.com/
PrivacyUrl: https://www.bluestacks.com/terms-and-privacy.html#privacy
Author: BlueStack Systems, Inc.
PackageName: BlueStacks
PackageUrl: https://support.bluestacks.com/hc/articles/360021469391
License: özel mülk
LicenseUrl: https://www.bluestacks.com/terms-and-privacy.html#terms
Copyright: >
  © 2011-2021 Bluestack Systems, Inc. Tüm hakları dünya çapında saklıdır
CopyrightUrl: https://www.bluestacks.com/copyright-dispute-policy.html
ShortDescription: Dünyanın En Hızlı, En Hafif Android Emülatörü ve Bulut Oyun platformu. Windows ve Mac'te mobil oyun oynayın. RPG, strateji ve aksiyon için mükemmel bir Emülatör.
Description: Dünyanın En Hızlı, En Hafif Android Emülatörü ve Bulut Oyun platformu. Windows ve Mac'te mobil oyun oynayın. RPG, strateji ve aksiyon için mükemmel bir Emülatör.
ReleaseNotes: |-
  1.  Artık herhangi bir oyun çökmesi olmadan ブ ル ー ア ー カ イ ブ (com.YostarJP.BlueArchive) oynayabilirsiniz. Artık sadece tarih kitaplarında bulunabilirler.
  2.  Siyah ekran, grafik ve çökme sorunlarının artık mevcut olmadığı fantastik AOD- 龍神 無双 - (com.coc.jplh) dünyasına girin!
  3.  Churchill Solitaire Card Game'de (com.productiveedge.churchill) yeni kayıtlar yapın çünkü açılış sahnesinden sonra artık çökmeyecek. Winston'ı gururlandırmanın zamanı geldi!
  4.  日 向 坂 46 と ふ し ぎ な 図 書 室 (jp.co.sonymusic.game.hinatosho) ile kusursuz bir oyun deneyimi için hazır olun!
  5.  Artık at ス ト オ リ ジ ン - 次世代 美 少女 × 戦 略 RPG- (com.pig.laojp.aos) oynayabilirsiniz. Bu destansı RPG'de insanlık için savaşın!
  6.  Rise of Kingdoms: Lost Crusade (com.lilithgame.roc.gp) oynarken, Ark of Osiris'te yama görmeyeceksiniz. Muhteşem bir oyun deneyimi ile gözlerinize ziyafet çekin.
  7.  프린세스 커넥트! Re: Dive (com.kakaogames.pcr) bir hata mesajı göstermeyecek ve başlatma sırasında çökmeyecek. Parlak zırhlı prenses şövalye olma zamanı!
ReleaseNotesUrl: https://support.bluestacks.com/hc/articles/360021469391
Documentations:
- DocumentLabel: BlueStacks 4
  DocumentUrl: https://support.bluestacks.com/hc/categories/360000451812
ManifestType: locale
ManifestVersion: 1.12.0
