# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: BlueStack.BlueStacks
PackageVersion: 4.280.1.1002
PackageLocale: it
Publisher: BlueStack Systems, Inc.
PublisherUrl: https://www.bluestacks.com/
PublisherSupportUrl: https://support.bluestacks.com/
PrivacyUrl: https://www.bluestacks.com/terms-and-privacy.html#privacy
Author: BlueStack Systems, Inc.
PackageName: BlueStacks
PackageUrl: https://support.bluestacks.com/hc/articles/360021469391
License: Proprietario
LicenseUrl: https://www.bluestacks.com/terms-and-privacy.html#terms
Copyright: >
  © 2011 fino al 2021 Bluestack Systems, Inc. Tutti i diritti riservati in tutto il mondo
CopyrightUrl: https://www.bluestacks.com/copyright-dispute-policy.html
ShortDescription: L'emulatore Android e la piattaforma di cloud gaming più veloci e leggeri al mondo. Gioca ai giochi mobili su Windows e Mac. Perfetto per giochi di ruolo, strategia e azione.
Description: L'emulatore Android e la piattaforma di cloud gaming più veloci e leggeri al mondo. Gioca ai giochi mobili su Windows e Mac. Perfetto per giochi di ruolo, strategia e azione.
ReleaseNotes: |-
  1. Ora puoi giocareブルーアーカイブ(com.YostarJP.BlueArchive) senza arresti anomali del gioco. Ora si trovano solo nei libri di storia.
  2. Entra nel fantastico mondo di AOD-龍神無双- (com.coc.jplh) dove non esistono più problemi di schermo nero, grafica e crash!
  3. Crea nuovi record in Churchill Solitaire Card Game (com.productiveedge.churcill) poiché non si bloccherà più dopo il film di apertura. È ora di rendere orgoglioso Winston!
  4. Preparati per un'esperienza di gioco impeccabile in日向坂46とふしぎな図書室(jp.co.sonymusic.game.hinatosho)!
  5. Ora puoi giocareラストオリジン –次世代美少女×戦略RPG- (com.pig.laojp.aos) senza crash all'avvio. Combatti per l'umanità in questo gioco di ruolo epico!
  6. Durante la riproduzione di Rise of Kingdoms: Lost Crusade  (com.lilithgame.roc.gp), non vedrai alcuna patch rosa nell'Arca di Osiride. Rifatevi gli occhi con una splendida esperienza di gioco.
  7. 커넥트! Re:Dive (com.kakaogames.pcr) non mostrerà un messaggio di errore e quindi si bloccherà all'avvio per te. È ora di essere il cavaliere principessa in armatura scintillante!
ReleaseNotesUrl: https://support.bluestacks.com/hc/articles/360021469391
Documentations:
- DocumentLabel: BlueStacks 4
  DocumentUrl: https://support.bluestacks.com/hc/categories/360000451812
ManifestType: locale
ManifestVersion: 1.12.0
