# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: BlueStack.BlueStacks
PackageVersion: 4.280.1.1002
PackageLocale: ru
Publisher: BlueStack Systems, Inc.
PublisherUrl: https://www.bluestacks.com/
PublisherSupportUrl: https://support.bluestacks.com/
PrivacyUrl: https://www.bluestacks.com/terms-and-privacy.html#privacy
Author: BlueStack Systems, Inc.
PackageName: BlueStacks
PackageUrl: https://support.bluestacks.com/hc/articles/360021469391
License: несвободные
LicenseUrl: https://www.bluestacks.com/terms-and-privacy.html#terms
Copyright: >
  © Bluestack Systems, Inc., 2011 - 2021. Все права защищены
CopyrightUrl: https://www.bluestacks.com/copyright-dispute-policy.html
ShortDescription: Самый быстрый и легкий Андроид Эмулятор и Облачная Игровая Платформа. Играй в мобильные игры на Windows и Mac. Идеально для РПГ, стратегий и экшен-игр.
Description: Самый быстрый и легкий Андроид Эмулятор и Облачная Игровая Платформа. Играй в мобильные игры на Windows и Mac. Идеально для РПГ, стратегий и экшен-игр.
ReleaseNotes: |-
  1. ブルーアーカイブ (com.YostarJP.BlueArchive). Решена проблема вылета игры.
  2. AOD-龍神無双- (com.coc.jplh). Устранены графические искажения, появление черного экрана и вылеты игры.
  3. Churchill Solitaire Card Game (com.productiveedge.churchill). Исправлены вылеты при открытии видеороликов в игре.
  4. 日向坂46とふしぎな図書室 (jp.co.sonymusic.game.hinatosho). Улучшена стабильность игрового процесса.
  5. ラストオリジン –次世代美少女×戦略RPG- (com.pig.laojp.aos). Решена проблема вылета игры.
  6. Rise of Kingdoms: Lost Crusade (com.lilithgame.roc.gp). Устранены розовые артефакты в событии «Ковчег Осириса».
  7. 프린세스 커넥트! Re:Dive (com.kakaogames.pcr). Решена проблема появления сообщения об ошибке при запуске игры.
ReleaseNotesUrl: https://support.bluestacks.com/hc/articles/360021469391
Documentations:
- DocumentLabel: BlueStacks 4
  DocumentUrl: https://support.bluestacks.com/hc/categories/360000451812
ManifestType: locale
ManifestVersion: 1.12.0
