# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: BlueStack.BlueStacks
PackageVersion: 4.280.1.1002
PackageLocale: zh-CN
Publisher: BlueStack Systems, Inc.
PublisherUrl: https://www.bluestacks.com/
PublisherSupportUrl: https://support.bluestacks.com/
PrivacyUrl: https://www.bluestacks.com/terms-and-privacy.html#privacy
Author: BlueStack Systems, Inc.
PackageName: BlueStacks
PackageUrl: https://support.bluestacks.com/hc/articles/360021469391
License: 专有软件
LicenseUrl: https://www.bluestacks.com/terms-and-privacy.html#terms
Copyright: ©2011年至2021年Bluestack Systems,Inc.在全世界保留所有權利
CopyrightUrl: https://www.bluestacks.com/copyright-dispute-policy.html
ShortDescription: 在电脑上玩安卓游戏，或从我们的云端立即体验
Description: 在电脑上玩安卓游戏，或从我们的云端立即体验
Tags:
- 安卓
- 模拟器
ReleaseNotes: |-
  1.  ブルーアーカイブ (com.YostarJP.BlueArchive)閃退問題修復
  2.  AOD-龍神無双- (com.coc.jplh)黑畫面問題修復
  3.  Churchill Solitaire Card Game (com.productiveedge.churchill) 建立新記錄時閃退問題已修復
  4. 日向坂46とふしぎな図書室 (jp.co.sonymusic.game.hinatosho)享受完美的遊戲體驗
  5. ラストオリジン –次世代美少女×戦略RPG- (com.pig.laojp.aos) 啟動時閃退問題已修復
  6. Rise of Kingdoms: Lost Crusade (com.lilithgame.roc.gp)畫面粉色方塊問題已修復
  7. 프린세스 커넥트! Re:Dive (com.kakaogames.pcr) 錯誤提示問題已修復
ReleaseNotesUrl: https://support.bluestacks.com/hc/articles/360021469391
InstallationNotes: |-
  使用此软件前，不妨考虑尝试[手机连接](https://support.microsoft.com/windows/apps/phonelink/phone-link-requirements-and-setup "“手机连接”要求和设置")作为替代方案。

  此版本特别适用于那些拥有 2~4 GB RAM 的电脑。了解更多关于系统要求的信息，请访问
  • [BlueStacks 4](https://support.bluestacks.com/hc/articles/360014581811 "BlueStacks 4 的系统要求")
  • [BlueStacks 5](https://support.bluestacks.com/hc/articles/360056129211 "BlueStacks 5 的系统要求")

  基于 Arm® 的电脑没有特别适用的可用发行版，默认获得提供 x64 发行版；这些发行版未做相应优化，从而在这些设备上几乎不可用，因此请勿在这些设备上安装本包。了解更多关于此问题的信息，请访问
  • [你的电脑的体系结构](https://support.microsoft.com/Windows/Experience/find-information-about-your-windows-device "查找有关 Windows 设备的信息")
  • [基于 ARM 的电脑常见问题解答](https://support.microsoft.com/windows/experience/platform-variants/windows-arm-based-pcs-faq "基于 Windows ARM 的电脑常见问题解答")

  无论你遇到什么故障，都请联系发布者以获取支持；特别是在本包在基于 Arm® 的 PC 上无法工作的情况下，请直接卸载此软件包。
Documentations:
- DocumentLabel: BlueStacks 4
  DocumentUrl: https://support.bluestacks.com/hc/categories/360000451812
ManifestType: locale
ManifestVersion: 1.12.0
