# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: BlueStack.BlueStacks
PackageVersion: 4.280.1.1002
PackageLocale: de
Publisher: BlueStack Systems, Inc.
PublisherUrl: https://www.bluestacks.com/
PublisherSupportUrl: https://support.bluestacks.com/
PrivacyUrl: https://www.bluestacks.com/terms-and-privacy.html#privacy
Author: BlueStack Systems, Inc.
PackageName: BlueStacks
PackageUrl: https://support.bluestacks.com/hc/articles/360021469391
License: Proprietäre
LicenseUrl: https://www.bluestacks.com/terms-and-privacy.html#terms
Copyright: >
  © 2011 bis 2021 Bluestack Systems, Inc. Alle Rechte weltweit vorbehalten
CopyrightUrl: https://www.bluestacks.com/copyright-dispute-policy.html
ShortDescription: Schnellster und leichtester Android Emulator und Cloud Gaming Plattform. Spiele Handyspiele auf Windows & Mac. Perfekt für RPG, Strategie- und Actionspiele.
Description: Schnellster und leichtester Android Emulator und Cloud Gaming Plattform. Spiele Handyspiele auf Windows & Mac. Perfekt für RPG, Strategie- und Actionspiele.
ReleaseNotes: |-
  1. Du kannst jetzt ブルーアーカイブ (com.YostarJP.BlueArchive) ohne Spielabstürze spielen. Sie können jetzt nur noch in Geschichtsbüchern gefunden werden.
  2. Betritt die fantastische Welt von AOD-龍神無双- (com.coc.jplh), in der es keine Blackscreens-, Grafik- und Absturzprobleme mehr gibt!
  3. Stelle neue Rekorde im Churchill Solitaire Kartenspiel (com.productiveedge.churchill) auf, da es nicht mehr nach dem Eröffnungsfilm abstürzt. Zeit, Winston stolz zu machen!
  4. Freue dich auf ein fehlerfreies Spielerlebnis in 日向坂46とふしぎな図書室 (jp.co.sonymusic.game.hinatosho)!
  5. Du kannst jetzt ラストオリジン -次世代美少女×戦略RPG- (com.pig.laojp.aos) ohne einen Absturz beim Start spielen. Kämpfe für die Menschheit in diesem epischen RPG!
  6. Während des Spiels Rise of Kingdoms: Lost Crusade (com.lilithgame.roc.gp), wirst du in Ark of Osiris keine rosa Flecken sehen. Gönne deinen Augen ein prächtiges Spielerlebnis.
  7. 프린세스 커넥트! Re:Dive (com.kakaogames.pcr) wird keine Fehlermeldung anzeigen und dann beim Start für dich abstürzen. Zeit, der Prinzessinnen-Ritter in glänzender Rüstung zu sein!
ReleaseNotesUrl: https://support.bluestacks.com/hc/articles/360021469391
Documentations:
- DocumentLabel: BlueStacks 4
  DocumentUrl: https://support.bluestacks.com/hc/categories/360000451812
ManifestType: locale
ManifestVersion: 1.12.0
