# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: BlueStack.BlueStacks
PackageVersion: 4.280.1.1002
PackageLocale: ar
Publisher: BlueStack Systems, Inc.
PublisherUrl: https://www.bluestacks.com/
PublisherSupportUrl: https://support.bluestacks.com/
PrivacyUrl: https://www.bluestacks.com/terms-and-privacy.html#privacy
Author: BlueStack Systems, Inc.
PackageName: BlueStacks
PackageUrl: https://support.bluestacks.com/hc/articles/360021469391
LicenseUrl: https://www.bluestacks.com/terms-and-privacy.html#terms
Copyright: >
  © 2011 حتى 2021 Bluestack Systems، Inc. جميع الحقوق محفوظة في جميع أنحاء العالم
CopyrightUrl: https://www.bluestacks.com/copyright-dispute-policy.html
ShortDescription: أسرع وأخف محاكي أندرويد ومنصة ألعاب سحابية في العالم. العب ألعاب الجوال على نظامي التشغيل ويندوز وماك. مثالية لألعاب RPG والاستراتيجية والحركة.
Description: أسرع وأخف محاكي أندرويد ومنصة ألعاب سحابية في العالم. العب ألعاب الجوال على نظامي التشغيل ويندوز وماك. مثالية لألعاب RPG والاستراتيجية والحركة.
ReleaseNotes: |-
  1. يمكنك الآن لعب ブ ル ー ア ー カ イ ブ (com.YostarJP.BlueArchive) دون أي أعطال باللعبة. لا يمكن العثور عليها الآن إلا في كتب التاريخ.
  2. ادخل إلى عالم AOD- 龍神 無双 الرائع - (com.coc.jplh) حيث لم تعد توجد مشكلات الشاشة السوداء والرسوم البيانية والأعطال!
  3. اصنع أرقامًا قياسية جديدة في لعبة بطاقات تشرشل سوليتير (com.producedge.churchill) لأنها لن تتعطل بعد الفيلم الافتتاحي بعد الآن. حان الوقت لجعل وينستون فخوراً!
  4. استعد لتجربة ألعاب لا تشوبها شائبة في 日 向 坂 46 と ふ し ぎ な 図 書 室 (jp.co.sonymusic.game.hinatosho)!
  5. يمكنك الآن تشغيل ラ ス ト オ リ ジ ン - 次世代 美 少女 × 戦 略 RPG- (com.pig.laojp.aos) بدون تعطل عند الإطلاق. حارب من أجل الإنسانية في لعبة تقمص الأدوار الملحمية هذه!
  6. أثناء لعب Rise of Kingdoms: Lost Crusade (com.lilithgame.roc.gp) ، لن ترى أي بقع وردية في Ark of Osiris. متع عينيك بتجربة لعب رائعة.
  7. 프린세스 커넥트! رد: لن يظهر Dive (com.kakaogames.pcr) رسالة خطأ ثم يتعطل عند الإطلاق نيابة عنك. حان الوقت لتكون أميرة الفارس بالدرع اللامع!
ReleaseNotesUrl: https://support.bluestacks.com/hc/articles/360021469391
Documentations:
- DocumentLabel: BlueStacks 4
  DocumentUrl: https://support.bluestacks.com/hc/categories/360000451812
ManifestType: locale
ManifestVersion: 1.12.0
