# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: BlueStack.BlueStacks
PackageVersion: 4.280.1.1002
PackageLocale: zh-TW
Publisher: BlueStack Systems, Inc.
PublisherUrl: https://www.bluestacks.com/
PublisherSupportUrl: https://support.bluestacks.com/
PrivacyUrl: https://www.bluestacks.com/terms-and-privacy.html#privacy
Author: BlueStack Systems, Inc.
PackageName: BlueStacks
PackageUrl: https://support.bluestacks.com/hc/articles/360021469391
License: 專有軟體
LicenseUrl: https://www.bluestacks.com/terms-and-privacy.html#terms
Copyright: >
  ©2011年至2021年Bluestack Systems,Inc.在全世界保留所有權利
CopyrightUrl: https://www.bluestacks.com/copyright-dispute-policy.html
ShortDescription: 世界上最快速、最輕便的Android模擬器和雲遊戲平臺。 在Windows和Mac端運行手機遊戲。 非常適合RPG、策略和動作遊戲。
Description: 世界上最快速、最輕便的Android模擬器和雲遊戲平臺。 在Windows和Mac端運行手機遊戲。 非常適合RPG、策略和動作遊戲。
ReleaseNotes: |-
  1.  ブルーアーカイブ (com.YostarJP.BlueArchive)閃退問題修復
  2.  AOD-龍神無双- (com.coc.jplh)黑畫面問題修復
  3.  Churchill Solitaire Card Game (com.productiveedge.churchill) 建立新記錄時閃退問題已修復
  4. 日向坂46とふしぎな図書室 (jp.co.sonymusic.game.hinatosho)享受完美的遊戲體驗
  5. ラストオリジン –次世代美少女×戦略RPG- (com.pig.laojp.aos) 啟動時閃退問題已修復
  6. Rise of Kingdoms: Lost Crusade (com.lilithgame.roc.gp)畫面粉色方塊問題已修復
  7. 프린세스 커넥트! Re:Dive (com.kakaogames.pcr) 錯誤提示問題已修復
ReleaseNotesUrl: https://support.bluestacks.com/hc/articles/360021469391
Documentations:
- DocumentLabel: BlueStacks 4
  DocumentUrl: https://support.bluestacks.com/hc/categories/360000451812
ManifestType: locale
ManifestVersion: 1.12.0
